config/routes.rb
# routes.rb
Rails.application.routes.draw do
  resources :password_resets, only: %i[new create edit update]
  resources :field_agencies
  resources :type_users do
    member do
      patch :toggle
      post :bind_field_type_user
      delete :unbind_field_type_user
    end
  end
  resources :field_type_users
  resources :updates
  resources :type_materials do
    member do
      post :append_spec_type_material
      delete :unbind_spec_type_material
    end
  end
  resources :user_sessions do
    collection do
      post :retrieve_credentials
    end
  end
  resources :spec_type_materials
  resources :sellers do
    member do
      post :bind_type_material
      delete :unbind_type_material
      post :bind_field_seller
      put :update_field_seller
      delete :unbind_field_seller
      delete :permanent_deletion
    end
  end
  resources :field_sellers
  resources :detentor_types, only: %i[index]
  resources :spec_materials
  resources :materials do
    collection do
      get :redefine_type_material
      get :redefine_seller_selected
      get :redefine_detentor_type
      get :redefine_material_selected
      get :get_all_specs_types
      get :get_all_field_sellers
    end
  end
  resources :procedures
  resources :agencies do
    collection do
      get :ping
      get :do_ping
    end
  end
  resources :categories do
    member do
      get :create_cats
    end
  end
  resources :sous_categories
  get 'pages/home'
  get 'pages/help'
  get 'pages/404'
  get 'pages/under_construction'

  resources :rights do
    collection do
      post :check_uncheck_right
    end
  end
  resources :file
  resources :sessions, only: %i[new create destroy]
  resources :incidents do
    member do
      get :update_subcats
      get :update_maxvalue_lvl_urgence
      get :send_tech_form
      get :order_by
      delete :cloture
      delete :reject
      put :reaffect
    end
  end
  resources :responses, only: :create
  resources :procedures do
    get :update_subcats
  end
  resources :users do
    member do
      get :allincidents
      get :to_treat
      get :download
      get :change_ip
      put :enable_disable
    end
    collection do
      get :forget_identifiers
      post :forget_identifiers
    end
  end
  get '/', to: 'user_sessions#new', as: :root
  get '/categories', to: 'categories#index'
  get '/sous_categories', to: 'sous_categories#index'
  get '/incidents', to: 'incidents#index'
  get '/signup', to: 'users#new', as: :signup
  get '/signin', to: 'user_sessions#new', as: :signin
  delete '/signout', to: 'user_sessions#destroy', as: :signout
  get '/rights', to: 'rights#index'
  get '/agencies', to: 'agencies#index'
  post '/attachments/upload', to: 'attachments#upload'
  put '/attachments/destroy', to: 'attachments#destroy'
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :users
  has_many :incidents
  has_many :field_agency_agencies, dependent: :destroy
  has_many :field_agencies, through: :field_agency_agencies

  # # Regexp for the postal code.
  # cp_regexp = /\A((0[1-9])|([1-8][0-9])|(9[0-8])|(2A)|(2B))[0-9]{3}\z/
  # # Regexp for email.
  # email_regexp = /\A[a-zA-Z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$\z/
  # # Regexp for phone number.
  # phone_regexp = /\A(0|\+33|0033)[1-9][0-9]{8}\z/
  # # Regexp for ip address.
  IP_REGEXP = /\A(?:(?:[1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}(?:[1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\z/

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }
  validates :ip_address, presence: true, format: { with: IP_REGEXP }
end

app/controllers/agencies_controller.rb
# agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: %i[show edit destroy]

  before_action :restrict_access
  before_action :agency_empty?, only: :destroy
  respond_to :json

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.order('name asc')
    respond_to do |format|
      format.json { render json: @agencies }
      format.html { render :index }
    end
  end

  # GET /agencies/ping
  def ping
    @agencies = Agency.all
    respond_to do |format|
      format.html { render :ping }
    end
  end

  # GET /agencies/do_ping
  def do_ping
    value = exec_ping(params[:host])
    render json: value
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
    respond_to do |format|
      format.json { render json: @agency }
      format.html { redirect_to edit_agency_url(@agency) }
    end
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
    @field_agencies = FieldAgency.all
  end

  # GET /agencies/1/edit
  def edit
    @field_agencies = FieldAgency.all
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(name: params[:agency][:name],
                         ip_address: params[:agency][:ip_address])
    if @agency.save
      render json: @agency.id, status: 201
    else
      render json: @agency.errors.full_messages, status: 422
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    if UpdateAgency.new(id: params[:id], params: agency_params).call
      render json: nil, status: 200
    else
      render json: nil, status: 422
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    respond_to do |format|
      @agency.destroy
      format.json { head :no_content }
      format.html { redirect_to agencies_url, notice: 'Opération réussie' }
    end
  end

  private

  def agency_empty?
    render json: "L'agence contient des utilisateurs", status: 422 if @agency
                                                                      .users
                                                                      .exists?
  end

  def set_agency
    @agency = Agency.find(params[:id])
  end

  def agency_params
    agency_params = params.require(:agency)
                          .permit(:name, :ip_address)
    agency_params[:data_agence_comp] = params[:agency][:data_agence_comp]
    agency_params.permit!
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
  def exec_ping(host)
    return 0 if host == 'NULL'
    @icmp = Net::Ping::ICMP.new(host)
    @icmp.ping ? (@icmp.duration * 1000).round(1) : 0
  end
end

app/views/agencies/_form.html.erb
<%= form_for(@agency) do |f| %>
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2">
    <div id="next">
      <div class="field form-group">
        <%= f.label "Nom" %>
        <%= f.text_field :name, class: "form-control next", placeholder: "Nom(champ requis)"%>
        <% if @agency.errors[:name].first != nil %>
        <div class="alert alert-danger ">
          <%= "Nom " + @agency.errors[:name].first%><br>
          <% if @agency.errors[:name].second != nil %>
          <%= "Nom " + @agency.errors[:name].second%><br>
          <% end %>
        </div>
        <!-- DIV ERROR -->
        <% end %>
      </div>
      <!-- #field#form-group -->
      <div class="field form-group">
        <%= f.label "Adresse IP" %>
        <%= f.text_field :ip_address, class: "form-control next", placeholder: "Adresse IP" %>
        <% if @agency.errors[:ip_address].first != nil %>
        <div class="alert alert-danger ">
          <%= "Adresse IP" + @agency.errors[:ip_address].first%><br>
          <% if @agency.errors[:ip_address].second != nil %>
          <%= "Adresse IP" + @agency.errors[:ip_address].second%><br>
          <% end %>
        </div>
        <!-- DIV ERROR -->
        <% end %>
      </div>
      <!-- #field#form-group -->
      <% if !@agency.id.nil? %>
      <strong>Informations supplémentaires :</strong>
      <% @field_agencies.each do |field_agency| %>
      <div class="field form-group" id="infos-comp">
        <strong><%= f.label "#{field_agency.name}" %></strong>
        <input
        type="text"
        name="<%= field_agency.name %>"
        value="<%= field_agency.field_agency_agencies.where(agency_id: @agency.id).first.content unless field_agency.field_agency_agencies.where(agency_id: @agency.id).first.nil? %>"
        class="form-control next field_agency_value"
        placeholder="<%= field_agency.name%>">
      </div>
      <% end %>
      <% end %>
    </div>
    <!-- #next -->
    <!-- BUTTONS -->
    <div class="actions form-group">
      <% unless @agency.id.nil? %>
      <button type="button" name="send-form" class="btn btn-flat btn-success form-control" data-id="<%= @agency.id %>">Valider</button><br><br>
      <% else %>
      <button type="button" name="send-form" class="btn btn-flat btn-success form-control" data-id="0">Valider</button><br><br>
      <% end %>
      <!-- <%= f.submit "Valider", id: "sendButton", class: "btn btn-flat btn-success form-control" %><br><br> -->
      <%= link_to 'Annuler', agencies_path, class: "btn btn-flat btn-danger form-control" %>
    </div>
  </div>
</div>
<% end %>
<!-- form_for -->
<% content_for :js do %>
<%= javascript_include_tag "agencies" %>
<% end %>

app/views/agencies/_modalCreateGraphics.html.erb
<div class="container-modal">
  <div class="modal fade" id="modalCreateGraphics" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Graphique des agences</h4>
        </div>
        <div class="modal-body">
          <div id="chart-1" style="height: 600px; width: 870px;"></div>
        </div>
        <div class="modal-footer">
          <button type="button" name='refresh' class="btn btn-flat btn-default btn-modal">Actualiser</button>
          <button type="button" class="btn btn-flat btn-danger btn-modal" data-dismiss="modal">Fermer</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/agencies/agenciesJavascript.html.erb
<script type="text/javascript">
$(document).ready(function(){
  $.pings = [];
  $.agencyName = "";
  $("").click(function(){
    $.ajax({ // demarage ajax
      url: '/agencies_createGraphics', // url du controller rails pour pinger (methode doPing)
      type: 'GET',
      dataType: 'script',
      data: {
        pings: $.pings, // transfert de l'adress ip dans params[:host] pour le récup dans le controller
        agencyName: $.agencyName
      },
      success: function(result){
        if (result == "false"){
          return false;
        }else{
          return true;
        }
      }
    });
  });


  // Script pour juste un seul ping (click sur bouton pinger)
  var booted = false;
  $.xhrPool = []; // array of uncompleted requests
  $.xhrPool.abortAll = function() { // our abort function
    $(this).each(function(idx, jqXHR) {
      jqXHR.abort(); // abortage
    });
    $.xhrPool.length = 0
  };
  $.ajaxSetup({
    beforeSend: function(jqXHR) { // before jQuery send the request we will push it to our array
      $.xhrPool.push(jqXHR); //insertion de la requete dans le pool
    },
  complete: function(jqXHR) { // when some of the requests completed it will splice from the array
    var index = $.xhrPool.indexOf(jqXHR); //recherche de lindex
      if (index > -1) {
        $.xhrPool.splice(index, 1);
      }
    }
  });

  $(".button_ping_agency").click(function(){
    if($(this).html() == "Ping" && booted == false){
      booted = true; // Vérouillage pour éviter les bugs
      var ipOfAgency = $(this).data("ip"); // Va chercher ce qui a dans data-ip="127.0.0.1"
      var idOfAgency = $(this).data("id"); // Va chercher ce qui a dans data-id="5"

      for(var i = 0; i <= 1000; i++){
        $.ajax({ // demarage ajax
          url: '/agencies_doPing', // url du controller rails pour pinger (methode doPing)
          type: 'GET',
          dataType: 'script',
          data: {
            host: ipOfAgency // transfert de l'adress ip dans params[:host] pour le récup dans le controller
          },
          success: function(result){
            if (result == "false"){ // peut retourner false si ip est null ou si TimeOut
              $("#agencyTd"+idOfAgency).replaceWith("<td id='agencyTd"+idOfAgency+"'>TimeOut</td>"); //ecriture du resultat dans le tableau
            }else{
              $.pings.push(parseInt(result));
              $("#agencyTd"+idOfAgency).replaceWith("<td id='agencyTd"+idOfAgency+"'>"+result+" ms</td>");//ecriture du resultat dans le tableau
            }
          }
        });
      }
    }
  });


// <!-- Script JS pour le bouton pinger toutes les agences -->
  $("#agencies_ping").click(function(){ // onclick
    for (var i = 0; i <= 30 ; i++){ // Reping 30 fois toute la liste (semblant de non-stop)
    $("#table_agencies > tbody > tr").each(function(){
      var id = $(this).data("id"); // trouve l'id de l'agence
      $.ajax({ // demarage ajax
        url: '/agencies_doPing', // url du controller rails pour pinger (methode doPing)
        type: 'GET',
        dataType: 'script',
        data: {
          host: $(this).data('ip') // transfert de l'adress ip dans params[:host]
        },
        success: function(result){
          if (result == "false"){ // peut retourner false si ip est null ou si TimeOut
            $("#agencyTd"+id).replaceWith("<td style='color: blue;'id='agencyTd"+id+"'>TimeOut</td>"); //ecriture du resultat dans le tableau
          }else if(result < 100){
            $("#agencyTd"+id).replaceWith("<td style='color: green;' id='agencyTd"+id+"'>"+result+" ms</td>");//ecriture du resultat dans le tableau
          }else if(result > 100 && result < 400){
            $("#agencyTd"+id).replaceWith("<td style='color: orange;' id='agencyTd"+id+"'>"+result+" ms</td>");//ecriture du resultat dans le tableau
          }else {
            $("#agencyTd"+id).replaceWith("<td style='color: red;' id='agencyTd"+id+"'>"+result+" ms</td>");//ecriture du resultat dans le tableau
          }
        }
      });
  });
}
  });
  $("#agencies_ping_cancel").click(function(){ // demande d'anulation de l'utilisateur
    $.xhrPool.abortAll(); // Appel a la fonction abortage
  });

// _____________________________________________________________________________________________

    $("#2nd").hide();
    $("#btn-creer-graphique").hide();
    $("#btn-suivant").click(function(){
      if($(this).html() == "Suivant"){
        $(this).html("Précédent");
        $("#1st").hide("slide", {direction: "left" }, 500);
        $("#2nd").show("slide", { direction: "right"}, 500);
        $("#btn-creer-graphique").show(500);
      }else if ($(this).html() == "Précédent") {
        $(this).html("Suivant");
        $("#2nd").hide("slide", {direction: "right" }, 500);
        $("#1st").show("slide", { direction: "left"}, 500);
        $("#btn-creer-graphique").hide(500);
      }else {
        return false;
      }
    });

    $("#btn-creer-graphique").click(function(){
      $.GraphicName = $("#graphicName").val();
      $.checkedAgencies = [];

      if($.checkedAgencies = []){return false;}
      if($.GraphicName = ""){return false;}

    });
  });

</script>

app/views/agencies/doPing.js.erb
$(".agency_ping_<%= @agency.id %>").replaceWith("<button class='showGraphicButton' data-toggle='modal' data-target='#showGraphic<%= @agency.id %>'>Afficher le graphique</p>");

app/views/agencies/edit.html.erb
<%= render 'form' %>

app/views/agencies/index.html.erb
<div class="table-responsive">
  <table class="table table-hover table-bordered dataTable" id='table_agencies'>
    <thead class="header">
      <tr>
        <th>Nom</th>
      </tr>
    </thead>
    <tbody>
      <% @agencies.each do |agency| %>
      <tr>
        <td class="hover-cellule <%= agency.id %>" data-toggle="modal" data-target="#<%= agency.id %>"><%= agency.name %></td>
      </tr>
      <!-- MODAL POUR CHAQUE AGENCE -->
      <div class="container-modal">
        <div class="modal fade" id="<%= agency.id %>" role="dialog">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <!-- HEADER DU MODAL -->
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Agence <%= agency.name%></h4>
                <i>Vous pouvez voir ici les détails de l'agence</i>
              </div>
              <!-- HEADER DU MODAL -->
              <!-- BODY DU MODAL -->
              <div class="modal-body">
                <% agency.field_agencies.each do |field_agency| %>
                <p><strong><%= field_agency.name %> : </strong><%= field_agency.field_agency_agencies.where(agency_id: agency.id).first.content %></p>
                <% end %>
              </div>
              <!-- BODY DU MODAL -->
              <!-- FOOTER DU MODAL -->
              <div class="modal-footer">
                <% if current_user.can?('destroy_agencies') %>
                <button type="button" name="destroy_agency" data-id="<%= agency.id %>" class="btn btn-flat btn-default btn-modal">Supprimer</button>
                <% end %>
                <% if current_user.can?('edit_agencies') %>
                <%= link_to "Editer", edit_agency_url(agency), class: 'btn btn-flat btn-info btn-modal'%>
                <% end %>
                <button type="button" class="btn btn-flat btn-danger btn-modal" data-dismiss="modal">Fermer</button>
              </div>
              <!-- FOOTER DU MODAL -->
            </div>
          </div>
        </div>
      </div>
      <!-- MODAL POUR CHAQUE AGENCE -->
      <% end %>
    </tbody>
  </table>
</div>

<% content_for :js do %>
  <% javascript_include_tag 'agencies' %>
<% end %>

app/views/agencies/new.html.erb
<%= render 'form' %>

app/views/agencies/ping.html.erb
<button type="button" name="button" class="btn btn-flat btn-success" id="agencies_ping">Pinger toutes les agences</button>
<button type="button" name="button" class="btn btn-flat btn-danger" id="agencies_ping_cancel">Stopper</button>
<button type="button" data-toggle="modal" data-target="#modalCreateGraphics" name="button" id="btn-do-graphic" class="btn btn-flat btn-default btn-do-graphic">Faire le graphique</button>
<div class="table-responsive">
  <table class="table table-hover table-bordered" id='table_agencies'>
    <thead>
      <tr>
        <th>Nom</th>
        <th>IP</th>
        <th>Ping</th>
        <th>Pong</th>
      </tr>
    </thead>
    <tbody>
      <% @agencies.each do |agency| %>
      <tr data-ip="<%= agency.ip_address %>" data-id="<%= agency.id %>" data-name="<%= agency.name %>">
        <td class="hover-cellule <%= agency.id %>" data-toggle="modal" data-target="#<%= agency.id %>"><%= agency.name %></td>
        <td class="hover-cellule <%= agency.id %>" data-toggle="modal" data-target="#<%= agency.id %>"><%= agency.ip_address == "NULL" ? "" : agency.ip_address %></td>
        <% if agency.ip_address != "NULL" %>
        <td id="agencyTd<%= agency.id %>" class="hover-cellule <%= agency.id %>">
          <button type="button" name="button" data-id="<%= agency.id %>" data-ip="<%= agency.ip_address%>" data-name="<%= agency.name %>" class="btn btn-flat btn-default button_ping_agency">Ping</button>
        </td>
        <td id="agencyTd<%= agency.id %>" class="hover-cellule <%= agency.id %>">
          <button type="button" name="button" data-id="<%= agency.id %>" data-ip="<%= agency.ip_address%>" data-name="<%= agency.name %>" class="btn btn-flat btn-default button_ping_stop_agency">Stop</button>
        </td>
        <% else %>
        <td></td>
        <td></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'modalCreateGraphics'%>
<% content_for :js do %>
  <%= javascript_include_tag 'agencies' %>
<% end %>

app/views/agencies/show.html.erb
<div class="table-responsive">
  <table class="table table-hover">
    <thead class="header">
      <tr>
        <th>Objet</th>
        <th>Contenu</th>
        <th>Demandeur</th>
        <th>Technicien</th>
        <th>Catégorie</th>
        <th>Sous-Categorie</th>
        <th>Date</th>
        <th>Etat</th>
      </tr>
    </thead>
    <tbody>
      <% @agency.incidents.order(["created_at desc"]).each do |incident| %>
      <tr>
        <td onClick="document.location.href='<%=edit_incident_path(incident)%>'"><%= incident.title %></td>
        <td onClick="document.location.href='<%=edit_incident_path(incident)%>'"><%= truncate(strip_tags(incident.content), length: 17) %></td>
        <td onClick="document.location.href='<%=edit_incident_path(incident)%>'"><%= incident.user.name %>
          <%=incident.user.surname%></td>
        <% if incident.tech_id != nil %>
        <td onClick="document.location.href='<%=edit_incident_path(incident)%>'"><% incident.tech.surname %>
          <%=incident.tech.name %></td>
      <% else %>
        <td onClick="document.location.href='<%=edit_incident_path(incident)%>'">Technicien non défini</td>
        <% end %>
        <td onClick="document.location.href='<%=edit_incident_path(incident)%>'"><%= incident.category.name %></td>
        <td onClick="document.location.href='<%=edit_incident_path(incident)%>'"><%= incident.sous_category.name %></td>
        <td onClick="document.location.href='<%=edit_incident_path(incident)%>'"><%= incident.created_at.strftime("%d %b %Y %H:%M") %></td>
        <% if current_user.type_user.is_tech == false %>
        <td onClick="document.location.href='<%=edit_incident_path(incident)%>'"><%= incident.incident_state_id_for_user.shortcut %></td>
      <% else %>
        <td onClick="document.location.href='<%=edit_incident_path(incident)%>'"><%= incident.incident_state_id_for_tech.shortcut %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>