config/routes.rb
# routes.rb
Rails.application.routes.draw do
  resources :password_resets, only: %i[new create edit update]
  resources :field_agencies
  resources :type_users do
    member do
      patch :toggle
      post :bind_field_type_user
      delete :unbind_field_type_user
    end
  end
  resources :field_type_users
  resources :updates
  resources :type_materials do
    member do
      post :append_spec_type_material
      delete :unbind_spec_type_material
    end
  end
  resources :user_sessions do
    collection do
      post :retrieve_credentials
    end
  end
  resources :spec_type_materials
  resources :sellers do
    member do
      post :bind_type_material
      delete :unbind_type_material
      post :bind_field_seller
      put :update_field_seller
      delete :unbind_field_seller
      delete :permanent_deletion
    end
  end
  resources :field_sellers
  resources :detentor_types, only: %i[index]
  resources :spec_materials
  resources :materials do
    collection do
      get :redefine_type_material
      get :redefine_seller_selected
      get :redefine_detentor_type
      get :redefine_material_selected
      get :get_all_specs_types
      get :get_all_field_sellers
    end
  end
  resources :procedures
  resources :agencies do
    collection do
      get :ping
      get :do_ping
    end
  end
  resources :categories do
    member do
      get :create_cats
    end
  end
  resources :sous_categories
  get 'pages/home'
  get 'pages/help'
  get 'pages/404'
  get 'pages/under_construction'

  resources :rights do
    collection do
      post :check_uncheck_right
    end
  end
  resources :file
  resources :sessions, only: %i[new create destroy]
  resources :incidents do
    member do
      get :update_subcats
      get :update_maxvalue_lvl_urgence
      get :send_tech_form
      get :order_by
      delete :cloture
      delete :reject
      put :reaffect
    end
  end
  resources :responses, only: :create
  resources :procedures do
    get :update_subcats
  end
  resources :users do
    member do
      get :allincidents
      get :to_treat
      get :download
      get :change_ip
      put :enable_disable
    end
    collection do
      get :forget_identifiers
      post :forget_identifiers
    end
  end
  get '/', to: 'user_sessions#new', as: :root
  get '/categories', to: 'categories#index'
  get '/sous_categories', to: 'sous_categories#index'
  get '/incidents', to: 'incidents#index'
  get '/signup', to: 'users#new', as: :signup
  get '/signin', to: 'user_sessions#new', as: :signin
  delete '/signout', to: 'user_sessions#destroy', as: :signout
  get '/rights', to: 'rights#index'
  get '/agencies', to: 'agencies#index'
  post '/attachments/upload', to: 'attachments#upload'
  put '/attachments/destroy', to: 'attachments#destroy'
end

app/models/update.rb
class Update < ActiveRecord::Base
  validates :changesMade, presence: true
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: %i[show edit update destroy]
  
  before_action :restrict_access

  # GET /updates
  # GET /updates.json
  def index
    @view_update = verify_right('view_update')
    if @view_update
      @title = 'Liste des mises à jour'
      @updates = Update.all
      respond_to do |format|
        format.json { render json: @updates }
        format.html { render :index }
      end
    else
      permission_denied
    end
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
    @view_update = verify_right('view_update')
    if @view_update
      @title = "Mise à jour numéro : #{@update.id}"
      respond_to do |format|
        format.json { render json: @update }
        format.html { render :show }
      end
    else
      permission_denied
    end
  end

  # GET /updates/new
  def new
    @create_update = verify_right('create_update')
    if @create_update
      @title = 'Nouvelle mise à jour'
      @update = Update.new
    else
      permission_denied
    end
  end

  # GET /updates/1/edit
  def edit
    @modify_update = verify_right('modify_update')
    if @modify_update
      @title = "Mise à jour numéro : #{@update.id}"
      respond_to :html
    else
      permission_denied
    end
  end

  # POST /updates
  # POST /updates.json
  def create
    @create_update = verify_right('create_update')
    if @create_update
      @update = Update.new(update_params)
      respond_to do |format|
        if @update.save
          @users = User.all
          @users.each do |user|
            user.update(maj: true)
          end
          format.json { render json: @update.id, status: :created }
          format.html { redirect_to @update, notice: 'La mise à jour a été crée, et grâce à toi BG !' }
        else
          format.json { render json: @update.errors.full_messages, status: 422 }
          format.html { render :new, notice: "Impossible de créer la mise à jour : #{@update.errors}" }
        end
      end
    else
      permission_denied
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    @modify_update = verify_right('modify_update')
    if @modify_update
      respond_to do |format|
        if @update.update(update_params)
          format.json { head :no_content }
          format.html { redirect_to @update, notice: 'La mise à jour a bien été editée' }
        else
          format.json { render json: @update.errors.full_messages, status: 422 }
          format.html { render :edit, notice: "Impossible d'éditer la mise à jour : #{@update.errors}" }
        end
      end
    else
      permission_denied
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @delete_update = verify_right('delete_update')
    if @delete_update
      respond_to do |format|
        if @update.destroy
          format.json { head :no_content }
          format.html { redirect_to updates_url, notice: 'Mise à jour supprimée !' }
        else
          format.json { render json: 'Impossible de supprimer la mise à jour !', status: 422 }
          format.html { redirect_to updates_url, notice: 'Impossible de supprimer la mise à jour !' }
        end
      end
    else
      permission_denied
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_update
    @update = Update.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def update_params
    params.require(:update).permit(:changesMade)
  end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_form.html.erb
<br>
<%= simple_form_for(@update) do |f| %>
  <div class="form-inputs">
    <%= f.cktext_area :changesMade %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Valider', class: "btn btn-flat btn-success" %>
    <%= link_to 'Annuler', updates_path, class: "btn btn-flat btn-warning" %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<%= render 'form' %>

app/views/updates/index.html.erb
<div class="table-responsive">
  <table class="table table-hover" id="table_updates">
    <thead class="header">
    <tr>
      <th>N°</th>
      <th>Modifications</th>
    </tr>
  </thead>

  <tbody>
    <% @updates.each do |update| %>
      <tr data-toggle="modal" data-target="#<%= update.id %>">
        <td><%= update.id %></td>
        <td><%= truncate(strip_tags(update.changesMade), length: 150) %></td>
      </tr>
      <div class="container-modal">
        <!-- Modal -->
        <div class="modal fade" id="<%= update.id %>" role="dialog">
          <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Mise à jour n° :
                  <%= update.id %></h4>
              </div>
              <div class="modal-body">
                <p><%= raw update.changesMade %></p>
              </div>
              <div class="modal-footer">
                <%= link_to "Détails", edit_update_path(update), class: "btn btn-flat btn-primary"%>
                <%= link_to 'Supprimer', @update, method: :delete, data: { confirm: 'Êtes vous sûr ?' }, class: 'btn btn-flat btn-warning' %>

                
              </div>
            </div>

          </div>
        </div>

      </div>

    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/updates/new.html.erb
<%= render 'form' %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Changes:</strong>
  <%= @update.changesMade %>
</p>

<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>