config/routes.rb
# routes.rb
Rails.application.routes.draw do
  resources :password_resets, only: %i[new create edit update]
  resources :field_agencies
  resources :type_users do
    member do
      patch :toggle
      post :bind_field_type_user
      delete :unbind_field_type_user
    end
  end
  resources :field_type_users
  resources :updates
  resources :type_materials do
    member do
      post :append_spec_type_material
      delete :unbind_spec_type_material
    end
  end
  resources :user_sessions do
    collection do
      post :retrieve_credentials
    end
  end
  resources :spec_type_materials
  resources :sellers do
    member do
      post :bind_type_material
      delete :unbind_type_material
      post :bind_field_seller
      put :update_field_seller
      delete :unbind_field_seller
      delete :permanent_deletion
    end
  end
  resources :field_sellers
  resources :detentor_types, only: %i[index]
  resources :spec_materials
  resources :materials do
    collection do
      get :redefine_type_material
      get :redefine_seller_selected
      get :redefine_detentor_type
      get :redefine_material_selected
      get :get_all_specs_types
      get :get_all_field_sellers
    end
  end
  resources :procedures
  resources :agencies do
    collection do
      get :ping
      get :do_ping
    end
  end
  resources :categories do
    member do
      get :create_cats
    end
  end
  resources :sous_categories
  get 'pages/home'
  get 'pages/help'
  get 'pages/404'
  get 'pages/under_construction'

  resources :rights do
    collection do
      post :check_uncheck_right
    end
  end
  resources :file
  resources :sessions, only: %i[new create destroy]
  resources :incidents do
    member do
      get :update_subcats
      get :update_maxvalue_lvl_urgence
      get :send_tech_form
      get :order_by
      delete :cloture
      delete :reject
      put :reaffect
    end
  end
  resources :responses, only: :create
  resources :procedures do
    get :update_subcats
  end
  resources :users do
    member do
      get :allincidents
      get :to_treat
      get :download
      get :change_ip
      put :enable_disable
    end
    collection do
      get :forget_identifiers
      post :forget_identifiers
    end
  end
  get '/', to: 'user_sessions#new', as: :root
  get '/categories', to: 'categories#index'
  get '/sous_categories', to: 'sous_categories#index'
  get '/incidents', to: 'incidents#index'
  get '/signup', to: 'users#new', as: :signup
  get '/signin', to: 'user_sessions#new', as: :signin
  delete '/signout', to: 'user_sessions#destroy', as: :signout
  get '/rights', to: 'rights#index'
  get '/agencies', to: 'agencies#index'
  post '/attachments/upload', to: 'attachments#upload'
  put '/attachments/destroy', to: 'attachments#destroy'
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  belongs_to :category, class_name: 'Category', foreign_key: 'category_id'
  belongs_to :sous_category, class_name: 'SousCategory', foreign_key: 'sous_category_id'
  has_many :MsgProcedure
  validates :nom, presence: true, length: { in: 0..254 }
  validates :contenu, presence: true, length: { in: 0..65_535 }
  validates :resolution, presence: true, length: { in: 0..65_535 }
  validates :category_id, presence: true
  validates :sous_category_id, presence: true
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: %i[show edit update destroy]
  before_action :set_categories_all, only: %i[index show edit new create]
  
  before_action :restrict_access
  # GET /procedures
  # GET /procedures.json
  # Should get and return all the procedures.
  def index
    @view_procedures = verify_right('view_procedures')
    if @view_procedures
      @title = 'Liste des procedures'
      @procedures = Procedure.all.reorder('created_at asc')
      @edit_procedure = verify_right('edit_procedure')
      respond_to do |format|
        format.json { render json: @procedures }
        format.html { render :index }
      end
    else
      permission_denied
    end
  end

  # GET /procedures/1
  # GET /procedures/1.json
  # Get and returns one procedure by params passed.
  def show
    @view_procedures = verify_right('view_procedures')
    if @view_procedures
      @title = 'Procedure N° ' + @procedure.id.to_s
      respond_to do |format|
        format.json { render json: @procedure }
        format.html { render :show }
      end
    else
      permission_denied
    end
  end

  # GET /procedures/new
  # Only used for web.
  # Should render new form.
  # It get the param 'nom', 'contenu', 'messages' passed by an incident.
  # You understand ? Incident => Procedure = DRY.
  def new
    @create_procedure = verify_right('create_procedure')
    if @create_procedure
      @title = 'Nouvelle procedure'
      @procedure = Procedure.new
      @nom = params[:nom]
      @contenu = params[:contenu]
      unless params[:messages].nil?
        @messages = params[:messages]
        @a = ''
        i = 0
        msg = @messages.split(';;')
        msg = msg.each do |m|
          i += 1
          @a = @a + '<h4><b><u>Message N° ' + i.to_s + ' : </u></b><h4>' + m + '<br>'
        end
      end
      @category_id = params[:category_id]
      @sous_category_id = params[:sous_category_id]
      if @category_id.nil?
        @sous_categories = SousCategory.where('category_id = ?', Category.first.id)
      else
        @sous_categories = SousCategory.where('category_id = ?', @category_id)
      end
    else
      permission_denied
    end
  end

  # This is the method for update the list of the subcatecories when
  # We want to create an procedure.
  # It do the job in ajax, when the user change the category selected.
  def update_subcats
    @sous_categories = SousCategory.where('category_id = ?',
                                          params[:category_id])
    respond_to do |format|
      format.js
    end
  end

  # GET /procedures/1/edit
  # Should render the edit form, for... edit an procedure !!
  def edit
    @edit_procedure = verify_right('edit_procedure')
    if @edit_procedure
      @title = 'Procedure N° ' + @procedure.id.to_s
      @sous_categories = SousCategory.where('category_id = ?', Category.first.id)
    else
      permission_denied
    end
  end

  # POST /procedures
  # POST /procedures.json
  # Should create an procedure, with files et cetera...
  def create
    @create_procedure = verify_right('create_procedure')
    if @create_procedure
      @procedure = Procedure.new(procedure_params)
      respond_to do |format|
        if @procedure.save
          # If there are files, it saves it here.
          unless params[:file_procedures].nil?
            params[:file_procedures]['file'].each do |a|
              @file_procedure = @procedure.file_procedures.create!(
                procedure_id: @procedure.id,
                file: a
              )
            end
          end
          format.json { render json: @procedure.id, status: :created }
          format.html { redirect_to @procedure, notice: 'La procedure a été créée.' }
        else
          format.json { render json: @procedure.errors.full_messages, status: 422 }
          format.html { redirect_to :back, notice: 'Impossible de créer la procedure.' + @procedure.errors }
        end
      end
    else
      permission_denied
    end
  end

  # PATCH/PUT /procedures/1
  # PATCH/PUT /procedures/1.json
  # Update the params of the procedure passed in params.
  def update
    @edit_procedure = verify_right('edit_procedure')
    if @edit_procedure
      respond_to do |format|
        if @procedure.update(procedure_params)
          format.json { head :no_content }
          format.html { redirect_to @procedure, notice: 'La procedure a été mise a jour.' }
        else
          format.json { render json: @procedure.errors.full_messages, status: 422 }
          format.html { redirect_to :back, notice: 'Impossible de modifier la procedure' }
        end
      end
    else
      permission_denied
    end
  end

  # DELETE /procedures/1
  # DELETE /procedures/1.json
  # Should destroy the procedure selected.
  def destroy
    @delete_procedure = verify_right('delete_procedure')
    if @delete_procedure
      respond_to do |format|
        if @procedure.destroy
          format.json { head :no_content }
          format.html { redirect_to procedures_url, notice: 'La procedure a été supprimée.' }
        else
          format.json { render json: @procedure.errors.full_messages, status: 422 }
          format.html { redirect_to :back, notice: "Impossible de supprimer la procedure. #{@procedure.errors}" }
        end
      end
    else
      permission_denied
    end
  end

  def download
    send_file "#{Rails.root}/public/uploads/procedures/#{@procedure.file_procedure.id}/#{@procedure.file_procedure.identifier}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_procedure
    @procedure = Procedure.find(params[:id])
  end

  def set_categories_all
    @categories = Category.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def procedure_params
    params.require(:procedure).permit(
      :nom, :contenu, :resolution, :category_id,
      :sous_category_id,
      file_procedures_attributes: [:file]
    )
  end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= form_for @procedure, html: { multipart: true } do |f| %>

  <br><div class="field">
    <%= f.label "Titre"%><br>
    <%= f.text_field :nom, size: "100", value: @nom, class: "form-control" %><br><br>
    <% if @procedure.errors[:title].first != nil %>
    <div class="alert alert-danger">
      <%= "Objet " + @procedure.errors[:title].first%><br><br><br>
    </div>
    <% end %>
  </div>
    <div class="field">
      <%= f.label "Problème rencontré"%><br>
      <%= f.cktext_area :contenu, :id => 'procedure_contenu procedure_contenu', ckeditor: {uiColor: '#DDDDDD'}, required: true, value: @contenu%><br>
    </div>
      <div class="field">
        <%= f.label "Résolution"%><br>
        <%= f.cktext_area :resolution, :id => 'procedure_resolution procedure_resolution', ckeditor: {uiColor: '#DDDDDD'}, required: true, value: @a%><br>
      </div>
      <div class="field">
        <%= f.label "Catégorie", :class => ''  %><br>
        <%= select_tag "procedure[category_id]", options_for_select(@categories.collect{|category| [category.name.titleize, category.id]}, selected: @category_id), {:class => "form-control ", include_blank: "", required: true}%><br>
        <%= select_tag "procedure[sous_category_id]", options_for_select(@sous_categories.collect{|sous_category| [sous_category.name.titleize, sous_category.id]}, selected: @sous_category_id), {:class => "form-control ", include_blank: "", required: true} %>
      </div>

  <div class="fallback" id="filesinputs">
    <%= f.label "Fichiers"%><br>
      <%= fields_for :file_procedures, @procedure.file_procedures do |i| %>
        <%= i.file_field :file, name: "file_procedures[file][]", multiple: true, id: "attachfile" %>
      <% end %>
  </div>

  <div class="form-actions">
    <%= f.submit "Valider", class: "btn btn-flat btn-success" %>
  </div>
<% end %>

app/views/procedures/_form_edit.html.erb
<%= form_for @procedure, html: { multipart: true } do |f| %>

  <br><div class="field">
    <%= f.label "Titre"%><br>
    <%= f.text_field :nom, size: "100", class: "form-control" %><br><br>
    <% if @procedure.errors[:title].first != nil %>
    <div class="alert alert-danger">
      <%= "Objet " + @procedure.errors[:title].first%><br><br><br>
    </div>
    <% end %>
  </div>
    <div class="field">
      <%= f.label "Problème rencontré"%><br>
      <%= f.cktext_area :contenu, :id => 'procedure_contenu procedure_contenu', ckeditor: {uiColor: '#DDDDDD'}, required: true%><br>
    </div>
      <div class="field">
        <%= f.label "Résolution"%><br>
        <%= f.cktext_area :resolution, :id => 'procedure_resolution procedure_resolution', ckeditor: {uiColor: '#DDDDDD'}, required: true%><br>
      </div>
      <div class="field">
        <%= f.label "Catégorie", :class => ''  %><br>
        <%= select_tag "procedure[category_id]", options_for_select(@categories.collect{|category| [category.name.titleize, category.id]}, selected: @procedure.category_id), {:class => "form-control ", include_blank: "", required: true}%><br>
        <%= select_tag "procedure[sous_category_id]", options_for_select(@sous_categories.collect{|sous_category| [sous_category.name.titleize, sous_category.id]}, selected: @procedure.sous_category_id), {:class => "form-control ", include_blank: "", required: true} %>
      </div>

  <div class="fallback" id="filesinputs">
    <%= f.label "Fichiers"%><br>
      <%= fields_for :file_procedures, @procedure.file_procedures do |i| %>
        <%= i.file_field :file, name: "file_procedures[file][]", multiple: true, id: "attachfile" %>
      <% end %>
  </div>

  <div class="form-actions">
    <%= f.submit "Valider", class: "btn btn-flat btn-success" %>
  </div>
<% end %>

app/views/procedures/edit.html.erb
<%= render 'form_edit' %>

app/views/procedures/index.html.erb
<div class="table-responsive">
  <table class="table table-hover table-bordered dataTable">
    <thead class="header">
      <tr>
        <th>Nom</th>
        <th>Contenu</th>
        <th>Categorie</th>
        <th>SousCategorie</th>
      </tr>
    </thead>
    <tbody>
      <% @procedures.each do |procedure| %>
      <tr>
        <td class="hover-cellule <%= procedure.id %>" data-toggle="modal" data-target="#<%= procedure.id %>"><%= truncate(strip_tags(procedure.nom), length: 50) %></td>
        <td class="hover-cellule <%= procedure.id %>" data-toggle="modal" data-target="#<%= procedure.id %>"><%= truncate(strip_tags(procedure.contenu), length: 50) %></td>
        <td class="hover-cellule <%= procedure.id %>" data-toggle="modal" data-target="#<%= procedure.id %>"><%= procedure.category.name%></td>
        <td class="hover-cellule <%= procedure.id %>" data-toggle="modal" data-target="#<%= procedure.id %>"><%= procedure.sous_category.name %></td>
      </tr>
      <div class="container-modal">
        <!-- Modal -->
        <div class="modal fade" id="<%= procedure.id %>" role="dialog">
          <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><%= truncate(strip_tags(procedure.nom), length: 50)%></h4>
              </div>
              <div class="modal-body">
                <p style="width:600px;"><%= strip_tags(procedure.contenu) %></p>
              </div>
              <div class="modal-footer">
                <% if @edit_procedure%>
                  <%= link_to "Editer", edit_procedure_path(procedure), class: "btn btn-flat btn-primary"%>
                <% end %>
                <%= link_to "Détails", procedure, class: "btn btn-flat btn-success"%>
                
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </tbody>
    <thead class="header">
      <tr>
        <th>Nom</th>
        <th>Contenu</th>
        <th>Categorie</th>
        <th>SousCategorie</th>
      </tr>
    </thead>
  </table>
</div>

<br>

app/views/procedures/new.html.erb
<%= render 'form' %>

app/views/procedures/show.html.erb
<div class="procedures">
<h1 class="procedure_nom">Problème rencontré :</h1>
<h1 class="">
  <!-- <strong>Nom:</strong> -->
  <%= @procedure.nom %>
</h1>

<h3 class="procedure_categorie">
  <strong>Categorie:</strong>
  <%= @procedure.category.name %>
</h3>

<h3 class="procedure_souscategorie">
  <strong>Sous categorie:</strong>
  <%= @procedure.sous_category.name %>
</h3>

<p class="procedure_contenu">
  <!-- <strong>Contenu:</strong> -->
  <%= raw @procedure.contenu %>
</p>
<br><hr><br>
<h1 class="procedure_resolution_title">Resolution:</h1>
<p class="procedure_resolution">
  <%= raw @procedure.resolution %>
</p>
<h1 class="procedure_file">Fichiers nécéssaires à la résolution :</h1>
<% @procedure.file_procedures.each do |file|%>
<% if file.content_type.include?("image") %>
<%= link_to "#{image_tag(file.file_url, size: '800x400')}".html_safe, file.file_url%>
<% else %>
<%= link_to("#{file.file_identifier}", file.file_url, action: :download, class: "form-control ") %>
<% end %>
<% end %>
</div>